kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:latest-ext
  commands:
    -
    - git submodule init
    - git submodule update --remote
    - hugo

- name: publish gh-page
  image: plugins/gh-pages
  settings:
    target_branch: gh-pages
    pages_directory: public/
    username:
      from_secret: github_username
    password:
      from_secret: github_password
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
