language: node_js
sudo: required
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
branchs:
  only:
    - master
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn global add hexo-cli
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
  local-dir: public/
  verbose: true
