language: node_js
sudo: required
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
branchs:
  only:
    - master
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn global add hexo-cli
before_insall:
  - openssl aes-256-cbc -K $encrypted_97d432d3ed20_key -iv $encrypted_97d432d3ed20_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 139.199.176.47\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - yarn install
script:
  - hexo clean
  - hexo generate
after_success:
  - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no' public/ ubuntu@139.199.176.47:/var/www/blog
