language: node_js
sudo: required
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
branchs:
  only:
    - master
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn global add hexo-cli
install:
  - yarn install
script:
  - hexo clean
  - hexo generate
after_success:
  - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no' public/ ubuntu@139.199.176.47:/var/www/blog
