baseURL = "https://helbing.github.io/blog/"
languageCode = "en"
defaultContentLanguage = "en"
title = "DEMO"
theme = "zozo"
hasCJKLanguage = true
summaryLength = 100
paginate = 4
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]
  name = "helbing"

[blackfriday]
  smartypants = false

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  #subTitle = "vthe site subtitle"
  #footerSlogan = "My spiritual home"
  #keywords = ["Hugo","theme","zozo"]
  #description = "Hugo theme zozo example site."
  enableMathJax = true
  enableSummary = true
  mainSections = ["posts","post"]

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/helbing"
  #twitter = " "
  #facebook = " "
  #weibo = " "
  #instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
